# Generated by Django 4.1 on 2024-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BngJobs',
        ),
        migrations.DeleteModel(
            name='PuneJobs',
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
