# Generated by Django 4.1 on 2024-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_delete_bngjobs_delete_punejobs_alter_hydjobs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=64),
        ),
    ]
